### ISSUE TITLE
chore: Use of virtual environment

### ISSUE THREAD

**Issue by data-miner00** [xRovern/xRovMiscellaneous#3]
For Python-based projects, it is better to create a virtual environment to have their own isolated environment when developing, as well as keep track of the dependencies. You may use the built-in [venv](https://docs.python.org/3/library/venv.html) to do so, but it is a bit complicated to use.

I suggest checking out [Pipenv](https://pipenv.pypa.io/en/latest/) as it is more intuitive and similar to Node.js's NPM. It will create a `Pipfile` (equivalent to `package.json` in Node.js) and a `Pipfile.lock` (equivalent to `package.lock.json`). 

You will need to install Pipenv first on your local

```
pip install pipenv
```

After that, `cd`  to your current directory and run the following to activate a virtual environment.

```
pipenv shell
```

If you have any dependencies to install, simply

```
pipenv install <my-package-name>
```

For more info, please refer to the [Pipenv docs](https://pipenv.pypa.io/en/latest/).

Cheers,
Shaun

**Comment by xRovern** [comment]
I prefer conda environment or venv :rofl:
can use makefile for the venv

**Comment by data-miner00** [comment]
hahaha, can also, but conda imo is overkill la. The software itself is kinda heavy and we most of the time don't need to use all the feature it provides, so having a self-managed environment is kinda better la😂
